table FPBI_ESTRELA_METAS
	lineageTag: 18490ef0-67a2-4d9e-b9e2-0719ab033f2f

	column SEQVENDEDOR
		dataType: string
		lineageTag: b4026c9e-c08d-4b5c-8874-7dd4ae649b15
		summarizeBy: none
		sourceColumn: SEQVENDEDOR

		annotation SummarizationSetBy = Automatic

	column SEQMETA
		dataType: double
		lineageTag: ca82a1f3-50fb-49e5-a12d-4d4626289e6a
		summarizeBy: sum
		sourceColumn: SEQMETA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column META
		dataType: string
		lineageTag: 96aae6a6-773a-44e2-a878-1a696b3f562d
		summarizeBy: none
		sourceColumn: META

		annotation SummarizationSetBy = Automatic

	column ANOMES
		dataType: string
		lineageTag: 9957e531-2995-4848-bb00-19a54210d072
		summarizeBy: none
		sourceColumn: ANOMES

		annotation SummarizationSetBy = Automatic

	column DTAVALIDADE
		dataType: dateTime
		formatString: General Date
		lineageTag: 1c71115d-7817-4008-8bee-4865ce40d1b7
		summarizeBy: none
		sourceColumn: DTAVALIDADE

		annotation SummarizationSetBy = Automatic

	column 'Meta Display' =
			
			VAR NomeMeta = FPBI_ESTRELA_METAS[META]
			VAR Dia = DAY(FPBI_ESTRELA_METAS[DTAVALIDADE])
			
			RETURN
			IF(
			    NomeMeta IN {
			        "MIX BOVINO",
			        "MIX SUINO",
			        "MIX INDUSTRIALIZADOS"
			    },
			    NomeMeta & " - " &
			        IF(Dia <= 15, "1ª Quinzena", "2ª Quinzena"),
			    NomeMeta
			)
		lineageTag: b889dc60-5978-46b1-bdf2-a9faf5f8dfcb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column VLRMETA
		dataType: double
		lineageTag: 0be0af0d-b533-4524-a63f-89c059eb4d28
		summarizeBy: sum
		sourceColumn: VLRMETA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VENDEDOR
		dataType: string
		lineageTag: 4ad46c00-0cf0-4384-b7b9-3fd22bf4cbe6
		summarizeBy: none
		sourceColumn: VENDEDOR

		annotation SummarizationSetBy = Automatic

	column SEQSUPERVISOR
		dataType: string
		lineageTag: b9087d5c-6936-4aa5-95bc-e91bd2888c4c
		summarizeBy: none
		sourceColumn: SEQSUPERVISOR

		annotation SummarizationSetBy = Automatic

	column SUPERVISOR
		dataType: string
		lineageTag: 63edf14e-779f-41a0-a42d-8077b742670b
		summarizeBy: none
		sourceColumn: SUPERVISOR

		annotation SummarizationSetBy = Automatic

	column SEQGERENTEVENDA
		dataType: string
		lineageTag: e9384451-f89c-4148-a744-b0634fe02e1b
		summarizeBy: none
		sourceColumn: SEQGERENTEVENDA

		annotation SummarizationSetBy = Automatic

	column GERENTEVENDA
		dataType: string
		lineageTag: 727af08a-649d-423c-9974-249b023700f9
		summarizeBy: none
		sourceColumn: GERENTEVENDA

		annotation SummarizationSetBy = Automatic

	column seqvendedor-seqmeta-anomes-dtavalidade
		dataType: string
		lineageTag: 0cfc7b82-4c85-4d20-96ea-06a013af9f00
		summarizeBy: none
		sourceColumn: seqvendedor-seqmeta-anomes-dtavalidade

		annotation SummarizationSetBy = Automatic

	partition FPBI_ESTRELA_METAS = m
		mode: import
		source =
				let
				    Fonte = Oracle.Database("datavale", [HierarchicalNavigation=true]),
				    DATAVALE = Fonte{[Schema="DATAVALE"]}[Data],
				    FPBI_ESTRELA_METAS1 = DATAVALE{[Name="FPBI_ESTRELA_METAS"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(FPBI_ESTRELA_METAS1,{{"SEQVENDEDOR", type text}}),
				
				    #"Coluna Ajustada" =
				        Table.AddColumn(
				            #"Tipo Alterado",
				            "VLRMETA_Ajustado",
				            each if [SEQMETA] = 17 then [VLRMETA] * 1 else [VLRMETA],
				            type number
				        ),
				
				    #"Remove Antiga" =
				        Table.RemoveColumns(#"Coluna Ajustada", {"VLRMETA"}),
				
				    #"Renomeia Nova" =
				        Table.RenameColumns(#"Remove Antiga", {{"VLRMETA_Ajustado", "VLRMETA"}}),
				    #"Consultas Mescladas" = Table.NestedJoin(#"Renomeia Nova", {"SEQVENDEDOR"}, DGEVQ_HIERARQUIAVENDANIVEL, {"SEQVENDEDOR"}, "DGEVQ_HIERARQUIAVENDANIVEL", JoinKind.LeftOuter),
				    #"DGEVQ_HIERARQUIAVENDANIVEL Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "DGEVQ_HIERARQUIAVENDANIVEL", {"VENDEDOR", "SEQSUPERVISOR", "SUPERVISOR", "SEQGERENTEVENDA", "GERENTEVENDA"}, {"VENDEDOR", "SEQSUPERVISOR", "SUPERVISOR", "SEQGERENTEVENDA", "GERENTEVENDA"}),
				    #"Coluna Mesclada Inserida" = Table.AddColumn(#"DGEVQ_HIERARQUIAVENDANIVEL Expandido", "seqvendedor-seqmeta-anomes-dtavalidade", each Text.Combine({[SEQVENDEDOR], Text.From([SEQMETA], "pt-BR"), [ANOMES], Text.From([DTAVALIDADE], "pt-BR")}, "-"), type text),
				    #"Duplicatas Removidas" = Table.Distinct(#"Coluna Mesclada Inserida", {"seqvendedor-seqmeta-anomes-dtavalidade"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

