EVALUATE
FILTER(
    ADDCOLUMNS(
        SUMMARIZE(
            FILTER(
                DCVV_META_VENDADEVOLUCAO,
                DCVV_META_VENDADEVOLUCAO[ANOMES] = "202605" &&
                DCVV_META_VENDADEVOLUCAO[SEQVENDEDOR] = "298987"
            ),
            DCVV_META_VENDADEVOLUCAO[SEQCLIENTE]
        ),
        "ValorLiquido",
            CALCULATE(
                SUM(DCVV_META_VENDADEVOLUCAO[VALOR])
            ),
        "PesoLiquido",
            CALCULATE(
                SUM(DCVV_META_VENDADEVOLUCAO[PESOVENDA]) -
                SUM(DCVV_META_VENDADEVOLUCAO[PESODEVOLUCAO])
            )
    ),
    [ValorLiquido] <= 0 &&
    [PesoLiquido] > 0
)