
EVALUATE
VAR AnoMesAtual = "202605"
VAR VendedorAtual = "278511"

RETURN
ROW(
    "Peso Bruto",
    CALCULATE(
        SUM(DCVV_META_VENDADEVOLUCAOMIX[PESOVENDA]),
        DCVV_META_VENDADEVOLUCAOMIX[ANOMES] = AnoMesAtual,
        DCVV_META_VENDADEVOLUCAOMIX[SEQVENDEDOR] = VendedorAtual
    ),

    "Peso Devolucao Bruto",
    CALCULATE(
        SUM(DCVV_META_VENDADEVOLUCAOMIX[PESODEVOLUCAO]),
        DCVV_META_VENDADEVOLUCAOMIX[ANOMES] = AnoMesAtual,
        DCVV_META_VENDADEVOLUCAOMIX[SEQVENDEDOR] = VendedorAtual
    )
)



EVALUATE
VAR AnoMesAtual = "202605"
VAR VendedorAtual = "278511"

RETURN
ROW(
    "Peso Mix Bovino 1Q",
    CALCULATE(
        SUM(DCVV_META_VENDADEVOLUCAOMIX[PESOVENDA]) -
        SUM(DCVV_META_VENDADEVOLUCAOMIX[PESODEVOLUCAO]),

        DCVV_META_VENDADEVOLUCAOMIX[ANOMES] = AnoMesAtual,
        DCVV_META_VENDADEVOLUCAOMIX[SEQVENDEDOR] = VendedorAtual,
        DCVV_META_VENDADEVOLUCAOMIX[GRUPOPROD] = "1",

        FILTER(
            DCVV_META_VENDADEVOLUCAOMIX,
            DAY(DCVV_META_VENDADEVOLUCAOMIX[DTAEMISSAO]) <= 15
        )
    )
)

