// Bem-vindo ao modo de exibição de consulta DAX! Saiba mais sobre consultas DAX em https://aka.ms/dax-queries.
// Clique com o botão direito do mouse em tabelas, colunas ou medidas no painel de dados para acessar consultas rápidas ou peça ajuda ao Copilot para escrever DAX.

// Selecione "Executar" para experimentar esta consulta DAX de exemplo.

EVALUATE
ROW(
    "Peso Suíno",
    VAR pesovenda =
        CALCULATE(
            SUM(DCVV_META_VENDADEVOLUCAO[PESOVENDA]),
            DCVV_META_VENDADEVOLUCAO[GRUPOPROD] = "2",
            DCVV_META_VENDADEVOLUCAO[ANOMES] = 202605,
            DCVV_META_VENDADEVOLUCAO[SEQVENDEDOR] = "278511"
        )

    VAR pesodevolucao =
        CALCULATE(
            SUM(DCVV_META_VENDADEVOLUCAO[PESODEVOLUCAO]),
            DCVV_META_VENDADEVOLUCAO[GRUPOPROD] = "2",
            DCVV_META_VENDADEVOLUCAO[ANOMES] = 202605,
            DCVV_META_VENDADEVOLUCAO[SEQVENDEDOR] = "278511"
        )

    RETURN
        pesovenda - pesodevolucao
)

