EVALUATE
ROW(
    "Peso ",
    VAR pesovenda =
        CALCULATE(
            SUM(DCVV_META_VENDADEVOLUCAOCOMERCIAL[PESOVENDA]),
            --DCVV_META_VENDADEVOLUCAO[GRUPOPROD] = "2",
            DCVV_META_VENDADEVOLUCAOCOMERCIAL[ANOMES] = "202605",
            DCVV_META_VENDADEVOLUCAOCOMERCIAL[SEQVENDEDOR] = "278511"
        )


    VAR pesodevolucao =
        CALCULATE(
            SUM(DCVV_META_VENDADEVOLUCAOCOMERCIAL[PESODEVOLUCAO]),
            --DCVV_META_VENDADEVOLUCAO[GRUPOPROD] = "2",
			DCVV_META_VENDADEVOLUCAOCOMERCIAL[ANOMES] = "202605",
            DCVV_META_VENDADEVOLUCAOCOMERCIAL[SEQVENDEDOR] = "278511"
        )

    RETURN
     DIVIDE(PesoDevolucao, PesoBruto, 0) * 100
)
